name: somachine
channels:
 - conda-forge
 - defaults
dependencies:
  - jupyter=1.0.*
  - python=3.7.6
  - tensorflow=1.15.0
  - contextlib2=0.6.*
  - lxml=4.5.*
  - cython=0.29.*
  - pillow=7.1.*
  - multiprocess=0.70.*
  - opencv=3.4.*
  - pytorch=1.2.*
  - torchvision=0.4.*
  - matplotlib=3.3.*
  - numpy=1.18.1
  - pandas=1.1.*
  - scikit-learn=0.22.*
  - libopencv=3.4.2
  - imbalanced-learn=0.7.*
  - py-opencv=3.4.2
  - requests=2.25.*
  - pip:
    - scikit-multilearn=0.2.*
    - arff=0.9
